import type { ValidationReport } from "@/lib/validation/types";

const BASE_STYLES = `
  * { box-sizing: border-box; }
  body { font-family: -apple-system, "Segoe UI", Arial, sans-serif; color: #171717; margin: 0; padding: 32px; font-size: 13px; }
  .header { display: flex; align-items: center; justify-content: space-between; border-bottom: 2px solid #6d5ef8; padding-bottom: 16px; margin-bottom: 24px; }
  .logo { font-weight: 700; font-size: 18px; letter-spacing: -0.02em; }
  .logo span { color: #6d5ef8; }
  .meta { text-align: right; color: #666; font-size: 11px; }
  h1 { font-size: 22px; margin: 0 0 4px; }
  h2 { font-size: 14px; margin: 28px 0 10px; padding-bottom: 6px; border-bottom: 1px solid #e5e5e5; }
  .subtitle { color: #666; margin-bottom: 20px; }
  .badge { display: inline-block; padding: 2px 8px; border-radius: 999px; font-size: 10px; font-weight: 600; margin-left: 6px; }
  .badge.low { background: #fef3c7; color: #92400e; }
  .badge.medium { background: #dbeafe; color: #1e40af; }
  .badge.high { background: #dcfce7; color: #166534; }
  .grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px; margin-bottom: 8px; }
  .stat { border: 1px solid #e5e5e5; border-radius: 8px; padding: 10px 12px; }
  .stat .label { color: #666; font-size: 10px; text-transform: uppercase; letter-spacing: 0.04em; }
  .stat .value { font-size: 16px; font-weight: 700; margin-top: 2px; }
  ul { margin: 0; padding-left: 18px; }
  li { margin-bottom: 4px; }
  table { width: 100%; border-collapse: collapse; font-size: 12px; }
  th, td { text-align: left; padding: 6px 8px; border-bottom: 1px solid #eee; }
  .footer { margin-top: 32px; padding-top: 12px; border-top: 1px solid #e5e5e5; color: #999; font-size: 10px; }
`;

function badge(level: "LOW" | "MEDIUM" | "HIGH") {
  return `<span class="badge ${level.toLowerCase()}">${level} CONFIDENCE</span>`;
}

function header(title: string, subtitle: string) {
  return `
    <div class="header">
      <div class="logo">AD<span>INTEL</span></div>
      <div class="meta">Generated ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}</div>
    </div>
    <h1>${title}</h1>
    <p class="subtitle">${subtitle}</p>
  `;
}

function footer() {
  return `<div class="footer">All estimated metrics are modeled and shown with confidence and methodology. This report is evidence for decision-making, not a guarantee of business outcomes. Generated by ADINTEL.</div>`;
}

export function renderValidationReportHtml(report: ValidationReport): string {
  return `<!doctype html><html><head><meta charset="utf-8"><style>${BASE_STYLES}</style></head><body>
    ${header(`Product Validation — ${report.productName}`, `Selling price: ${report.currency} ${report.sellingPrice}`)}

    <h2>Validation summary ${badge(report.aiAssessment.confidence)}</h2>
    <p>${report.aiAssessment.summary}</p>

    <h2>Market signals</h2>
    <div class="grid">
      ${report.marketSignals.map((s) => `<div class="stat"><div class="label">${s.label}</div><div class="value">${s.value}</div><div style="font-size:11px;color:#666;margin-top:4px">${s.explanation}</div></div>`).join("")}
    </div>

    <h2>Competitor activity</h2>
    ${
      report.competitorActivity.length
        ? `<table><thead><tr><th>Store</th><th>Active ads</th><th>Platforms</th><th>Price</th></tr></thead><tbody>
      ${report.competitorActivity.map((c) => `<tr><td>${c.name}</td><td>${c.activeAds}/${c.totalAds}</td><td>${c.platforms.join(", ") || "—"}</td><td>${c.price !== null ? `${c.currency} ${c.price}` : "—"}</td></tr>`).join("")}
      </tbody></table>`
        : `<p>No tracked competitors currently sell a similarly named product.</p>`
    }

    <h2>Ad signals</h2>
    <div class="grid">
      <div class="stat"><div class="label">Total ads</div><div class="value">${report.adSignals.totalAds}</div></div>
      <div class="stat"><div class="label">Active ads</div><div class="value">${report.adSignals.activeAds}</div></div>
      <div class="stat"><div class="label">Distinct angles</div><div class="value">${report.adSignals.angles.length}</div></div>
    </div>

    <h2>Business estimates</h2>
    ${
      report.businessEstimates
        ? `<div class="grid">
      <div class="stat"><div class="label">Est. monthly revenue</div><div class="value">${report.businessEstimates.currency} ${report.businessEstimates.revenueLow}–${report.businessEstimates.revenueHigh}</div></div>
      <div class="stat"><div class="label">Est. monthly traffic</div><div class="value">${report.businessEstimates.trafficLow}–${report.businessEstimates.trafficHigh}</div></div>
    </div>`
        : `<p>Insufficient public data to estimate business scale for this product.</p>`
    }

    <h2>Unit economics</h2>
    ${
      report.unitEconomics
        ? `<div class="grid">
      <div class="stat"><div class="label">Gross profit / order</div><div class="value">${report.currency} ${report.unitEconomics.grossProfitPerOrder}</div></div>
      <div class="stat"><div class="label">Gross margin</div><div class="value">${report.unitEconomics.grossMarginPct}%</div></div>
      <div class="stat"><div class="label">Break-even ROAS</div><div class="value">${Number.isFinite(report.unitEconomics.breakEvenROAS) ? report.unitEconomics.breakEvenROAS + "x" : "N/A"}</div></div>
    </div>`
        : `<p>Add a product cost to calculate unit economics.</p>`
    }

    <h2>Risks to investigate</h2>
    <ul>${report.aiAssessment.risks.map((r) => `<li>${r}</li>`).join("")}</ul>

    <h2>Questions before testing</h2>
    <ul>${report.aiAssessment.questionsToInvestigate.map((r) => `<li>${r}</li>`).join("")}</ul>

    <h2>Methodology</h2>
    <p>Market and ad signals are computed from stores and products tracked in this workspace. Business estimates are aggregated from per-store traffic and revenue models (traffic × conversion × AOV). Unit economics use standard payment fee (2.9%) and refund rate (5%) assumptions. AI assessment is generated from this evidence only and never guarantees outcomes.</p>

    ${footer()}
  </body></html>`;
}

export interface StoreReportData {
  name: string;
  domain: string;
  category: string | null;
  platform: string | null;
  country: string | null;
  currency: string;
  productCount: number;
  activeAdCount: number;
  totalAdCount: number;
  signals: { label: string; value: string; explanation: string }[];
  revenue: { monthlyLow: number; monthlyHigh: number; confidence: "LOW" | "MEDIUM" | "HIGH"; methodology: string } | null;
  traffic: { monthlyVisitsLow: number; monthlyVisitsHigh: number; confidence: "LOW" | "MEDIUM" | "HIGH" } | null;
}

export function renderStoreReportHtml(data: StoreReportData): string {
  return `<!doctype html><html><head><meta charset="utf-8"><style>${BASE_STYLES}</style></head><body>
    ${header(`Store Analysis — ${data.name}`, `${data.domain}${data.category ? ` · ${data.category}` : ""}${data.platform ? ` · ${data.platform}` : ""}`)}

    <h2>Overview</h2>
    <div class="grid">
      <div class="stat"><div class="label">Products detected</div><div class="value">${data.productCount}</div></div>
      <div class="stat"><div class="label">Active ads</div><div class="value">${data.activeAdCount} / ${data.totalAdCount}</div></div>
      <div class="stat"><div class="label">Country</div><div class="value">${data.country ?? "Unknown"}</div></div>
    </div>

    <h2>Validation signals</h2>
    <div class="grid">
      ${data.signals.map((s) => `<div class="stat"><div class="label">${s.label}</div><div class="value">${s.value}</div><div style="font-size:11px;color:#666;margin-top:4px">${s.explanation}</div></div>`).join("")}
    </div>

    <h2>Business estimates</h2>
    ${
      data.revenue
        ? `<div class="grid">
      <div class="stat"><div class="label">Est. monthly revenue ${badge(data.revenue.confidence)}</div><div class="value">${data.currency} ${data.revenue.monthlyLow}–${data.revenue.monthlyHigh}</div></div>
      ${data.traffic ? `<div class="stat"><div class="label">Est. monthly traffic ${badge(data.traffic.confidence)}</div><div class="value">${data.traffic.monthlyVisitsLow}–${data.traffic.monthlyVisitsHigh}</div></div>` : ""}
    </div>
    <p style="color:#666;font-size:11px">${data.revenue.methodology}</p>`
        : `<p>Insufficient public data to estimate revenue for this store.</p>`
    }

    <h2>Methodology</h2>
    <p>Store, product and ad data reflect what ADINTEL observed from supported public sources at the time of analysis. Traffic and revenue are modeled estimates, not verified analytics — always shown as a range with an explicit confidence level.</p>

    ${footer()}
  </body></html>`;
}
